use_frameworks!

target 'PersistentUUID_Example' do
  pod 'PersistentUUID', :path => '../'

  target 'PersistentUUID_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
