use_frameworks!

target 'PersistentUUID_Example' do
  pod 'PersistentUUID', :path => '../'

  target 'PersistentUUID_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
